#Key Adapters
#Fri May 01 00:40:16 EDT 2026
tooltipoverhaul.binds.compare_bind=controllable.button.right_trigger
key.puffish_skills.open=
key.ponder.ponder=
key.sophisticatedcore.sort=controllable.button.right_thumb_stick
key.journeymap.zoom_in=controllable.button.right_trigger
key.ftbquests.quests=
quark.keybind.sort_player=controllable.button.left_thumb_stick
key.ok_zoomer.increase_zoom=controllable.button.right_trigger
key.journeymap.zoom_out=controllable.button.left_trigger
key.journeymap.create_waypoint=
key.journeymap.minimap_type=
quark.keybind.transfer_extract=
quark.keybind.transfer_insert=
key.ok_zoomer.zoom=controllable.button.dpad_up
key.ok_zoomer.decrease_zoom=controllable.button.left_trigger
quark.keybind.sort_container=controllable.button.right_thumb_stick
key.journeymap.map_toggle_alt=
key.stardew_fishing.minigame_button=controllable.button.a
key.sophisticatedbackpacks.open_backpack=
