#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 30 13:41:25 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.6.1 + Clrwl_1.0.4.zip
enableShaders=false
